### ISSUE TITLE
Issues with permalinking

### ISSUE THREAD

**Issue by trentv4** [okofish/xkcd37bot#1]
https://www.reddit.com/r/xkcd/comments/383mpd/hi_im_a_new_xkcdrelated_bot/crt456e

sweet-ass [testing](http://google.com) 

becomes

*sweet ass-[testing](http

**Comment by okofish** [comment]
This happens because the bot stops at full colons. I consider this occurence minimal priority because this sort of formatting likely won't be encountered much outside of the bot's announcement thred.
